// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: workbook/workbook.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorkbookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Org   *string `protobuf:"bytes,2,opt,name=org,proto3,oneof" json:"org,omitempty"`
	Name  string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateWorkbookRequest) Reset() {
	*x = CreateWorkbookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workbook_workbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkbookRequest) ProtoMessage() {}

func (x *CreateWorkbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workbook_workbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkbookRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkbookRequest) Descriptor() ([]byte, []int) {
	return file_workbook_workbook_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorkbookRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateWorkbookRequest) GetOrg() string {
	if x != nil && x.Org != nil {
		return *x.Org
	}
	return ""
}

func (x *CreateWorkbookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteWorkbookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Org        *string `protobuf:"bytes,2,opt,name=org,proto3,oneof" json:"org,omitempty"`
	WorkbookId string  `protobuf:"bytes,3,opt,name=workbook_id,json=workbookId,proto3" json:"workbook_id,omitempty"`
}

func (x *DeleteWorkbookRequest) Reset() {
	*x = DeleteWorkbookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workbook_workbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteWorkbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkbookRequest) ProtoMessage() {}

func (x *DeleteWorkbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workbook_workbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkbookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkbookRequest) Descriptor() ([]byte, []int) {
	return file_workbook_workbook_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteWorkbookRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DeleteWorkbookRequest) GetOrg() string {
	if x != nil && x.Org != nil {
		return *x.Org
	}
	return ""
}

func (x *DeleteWorkbookRequest) GetWorkbookId() string {
	if x != nil {
		return x.WorkbookId
	}
	return ""
}

var File_workbook_workbook_proto protoreflect.FileDescriptor

var file_workbook_workbook_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x62,
	0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x6c,
	0x61, 0x62, 0x2e, 0x72, 0x70, 0x63, 0x22, 0x60, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6f, 0x72, 0x67, 0x22, 0x6d, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x88, 0x01, 0x01, 0x12, 0x1f,
	0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x64, 0x42,
	0x06, 0x0a, 0x04, 0x5f, 0x6f, 0x72, 0x67, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x61, 0x62, 0x65, 0x72, 0x65, 0x69, 0x73, 0x65, 0x72,
	0x2f, 0x64, 0x61, 0x74, 0x61, 0x6c, 0x61, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workbook_workbook_proto_rawDescOnce sync.Once
	file_workbook_workbook_proto_rawDescData = file_workbook_workbook_proto_rawDesc
)

func file_workbook_workbook_proto_rawDescGZIP() []byte {
	file_workbook_workbook_proto_rawDescOnce.Do(func() {
		file_workbook_workbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_workbook_workbook_proto_rawDescData)
	})
	return file_workbook_workbook_proto_rawDescData
}

var file_workbook_workbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workbook_workbook_proto_goTypes = []interface{}{
	(*CreateWorkbookRequest)(nil), // 0: datalab.rpc.CreateWorkbookRequest
	(*DeleteWorkbookRequest)(nil), // 1: datalab.rpc.DeleteWorkbookRequest
}
var file_workbook_workbook_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workbook_workbook_proto_init() }
func file_workbook_workbook_proto_init() {
	if File_workbook_workbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workbook_workbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkbookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workbook_workbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteWorkbookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_workbook_workbook_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_workbook_workbook_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workbook_workbook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workbook_workbook_proto_goTypes,
		DependencyIndexes: file_workbook_workbook_proto_depIdxs,
		MessageInfos:      file_workbook_workbook_proto_msgTypes,
	}.Build()
	File_workbook_workbook_proto = out.File
	file_workbook_workbook_proto_rawDesc = nil
	file_workbook_workbook_proto_goTypes = nil
	file_workbook_workbook_proto_depIdxs = nil
}
